version: '3'
services:
  stun:
    image: bprodoehl/turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"

  janus:
    image: atyenoria/janus-webrtc-gateway-docker
    ports:
      - "8088:8088" 
    volumes:
      - /root/kien/transcoder/docker-gstreamer:/tmp
      - ./ssl:/etc/ssl
      - ./janus:/usr/local/etc/janus 
    depends_on:
      - stun
    command: janus -d 7 -S deploy_stun_1:3478
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8089:8089"
      - "8188:8188"
      - "8989:8989"
    depends_on:
      - janus
 
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./demos:/opt/demos
      - ./ssl:/etc/ssl
