version: '3'
services:
  stun:
    image: bprodoehl/turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"

  janus:
    image: atyenoria/janus-webrtc-gateway-docker
    ports:
      - "8088:8088" 
    volumes:
      - /root/kien/transcoder/docker-gstreamer:/tmp
      - ./ssl:/etc/ssl 
    depends_on:
      - stun
    command: janus -c /etc/ssl/certs/nginx-selfsigned.crt -k /etc/ssl/private/nginx-selfsigned.key  -S deploy_stun_1:3478    

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8089:8089"
      - "8188:8188"
    depends_on:
      - janus
 
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./demos:/opt/demos
      - ./ssl:/etc/ssl
