version: '3'
services:
  stun:
    image: bprodoehl/turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"

  janus:
    image: atyenoria/janus-webrtc-gateway-docker
    ports:
      - "8088:8088" 
      - "8089:8089" 
      - "8898:8989" 
    volumes:
      - /root/kien/transcoder/docker-gstreamer:/tmp
      - ./ssl:/etc/ssl
      - ./janus:/usr/local/etc/janus 
    depends_on:
      - stun
    command: janus -d 7 

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - janus
 
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./demos:/opt/demos
      - ./ssl:/etc/ssl
