version: '3'
services:
  stun:
    image: instrumentisto/coturn
    network_mode: host
    command: -n --log-file=stdout  --external-ip=167.71.198.191
    volumns:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
  janus:
    image: atyenoria/janus-webrtc-gateway-docker
    ports:
      - "8088:8088" 
      - "8089:8089" 
      - "8898:8989" 
 
    volumes:
      - /tmp:/tmp
      - ./ssl:/etc/ssl
      - ./janus:/usr/local/etc/janus 
    depends_on:
      - stun
    command: janus

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - janus
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./demos:/opt/demos
      - ./ssl:/etc/ssl
